# Configuration optimisée par ton Senior Dev
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: local
    hooks:
      - id: trivy-scan
        name: Trivy Security Scan
        # Cette ligne appelle le Trivy que tu as installé sur ta machine
        entry: trivy fs --exit-code 1 --severity HIGH,CRITICAL .
        language: system
        pass_filenames: false
