repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: local
    hooks:
      - id: trivy-scan
        name: Trivy Security Scan
        entry: trivy fs --exit-code 1 --severity HIGH,CRITICAL .
        language: system
        pass_filenames: false

- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v3.1.0
  hooks:
    - id: conventional-pre-commit
      stages: [commit-msg]
      args: [feat, fix, chore, docs, style, refactor, perf, test]
