name: pre-commit

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - develop

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install Trivy
        run: |
          sudo apt-get install wget gnupg lsb-release -y
          wget -qO - https://aquasecurity.github.io/trivy-repo/dab/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy -y

      - uses: pre-commit/action@v3.0.1
